apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
      tier: backend
  template:
    metadata:
      labels:
        app: story-app
        tier: backend
    spec:
      containers:
        - name: story-app-pod
          image: ashishyd/kub-story-node-app:latest
          imagePullPolicy: Always
          env:
            - name: STORY_FOLDER
              # value: /story
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-app-volume
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: story-app-volume
          # emptyDir: {}
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
      